version: '3.9'

services:
  php:
    image: myparcelnl/php-sdk
    build: ./
    env_file:
      - .env
    volumes:
      - ./:/app

  pest:
    image: myparcelnl/php-sdk
    build:
      context: ./
      target: test
    init: true
    env_file:
      - .env
    volumes:
      - ./:/app
