name: 'Create checks'
description: 'Create commit checks'

inputs:
  token:
    description: 'GitHub token.'
    required: false

  checks:
    description: 'Comma separated check names.'
    required: true

  conclusion:
    description: 'Conclusion of the check(s).'
    default: 'success'

  status:
    description: 'Status of the check(s).'
    default: 'completed'

runs:
  using: composite
  steps:
    - uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.token }}
        script: |
          let checks = `${{ inputs.checks }}`.split(/[\n,]/);

          await Promise.all(checks.map(async check => {
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: context.sha,
              name: check.trim(),
              status: '${{ inputs.status }}',
              conclusion: '${{ inputs.conclusion }}',
            });
          }));
