name: 'Semantic release'
description: 'Run semantic release'

inputs:
  token:
    description: 'GitHub Personal access token'
    required: true

  semantic-release-args:
    description: 'Semantic release arguments'
    required: false

  write-summary:
    description: 'Write a summary to the GitHub action output'
    required: false
    default: 'false'

outputs:
  version:
    description: 'The new version'
    value: ${{ steps.semantic-release.outputs.version }}

  previous-version:
    description: 'The previous version'
    value: ${{ steps.semantic-release.outputs.previous-version }}

  released:
    description: 'Whether a new version was released'
    value: ${{ steps.semantic-release.outputs.released }}

runs:
  using: composite
  steps:
    - name: 'Run semantic release'
      run: npx semantic-release ${{ inputs.semantic-release-args }}
      id: semantic-release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}

    - name: 'Check outputs'
      shell: bash
      run: |
        echo ${{ steps.semantic-release.outputs.lastVersion }}
        echo ${{ steps.semantic-release.outputs.releaseType }}
        echo ${{ steps.semantic-release.outputs.nextVersion }}

    - name: 'Write job summary'
      if: ${{ inputs.write-summary == 'true' }}
      shell: bash
      run: |
        REPO_URL="https://github.com/${{ github.repository }}"
        LAST_VER=${{ steps.semantic-release.outputs.lastVersion }}
        NEXT_VER=${{ steps.semantic-release.outputs.nextVersion }}

        echo "# Release summary" >> $GITHUB_STEP_SUMMARY

        if [ "${{ steps.semantic-release.outputs.released }}" == "true" ]; then
          echo "A new version was released: [$NEXT_VER]($REPO_URL/releases/tag/$NEXT_VER)"      >> $GITHUB_STEP_SUMMARY
          echo ""                                                                               >> $GITHUB_STEP_SUMMARY
          echo "## Commits in this release"                                                     >> $GITHUB_STEP_SUMMARY
          echo ""                                                                               >> $GITHUB_STEP_SUMMARY
          echo "| Summary | Commit |"                                                           >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |"                                                                  >> $GITHUB_STEP_SUMMARY
          git log --pretty=format:"| %s | [%h]($REPO_URL/commit/%H) |" ${LAST_VER}..${NEXT_VER} >> $GITHUB_STEP_SUMMARY
        else
          echo "No new version was released." >> $GITHUB_STEP_SUMMARY
        fi
