name: 'Install yarn dependencies'
description: 'Install yarn dependencies from scratch or from cache'

inputs:
  node-version:
    description: 'The Node.js version to use'
    default: '16'
    required: false

runs:
  using: composite
  steps:
    - uses: ./deprecate
      with:
        action-name: ${{ github.action_path }}@${{ github.action_ref }}
        replacement: 'myparcelnl/actions/yarn-install@v3'

    - uses: myparcelnl/actions/yarn2-install@v3
      with:
        node-version: ${{ inputs.node-version }}
