name: Install yarn dependencies
description: Install yarn dependencies from scratch or from cache

inputs:
  node-version:
    description: 'The Node.js version to use'
    default: '16'
    required: false

runs:
  using: composite
  steps:
    - uses: myparcelnl/actions/setup-node@v1
      with:
        node-version: ${{ inputs.node-version }}

    - name: 'Prepare node_modules cache'
      uses: actions/cache@v2
      id: yarn-cache
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: 'Install yarn dependencies'
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile
      shell: bash
