name: 'Install pnpm dependencies'
description: 'Install pnpm dependencies from scratch or from cache'

inputs:
  node-version:
    description: 'The Node.js version to use'
    default: '20'
    required: false

  pnpm-version:
    description: 'The pnpm version to use'
    default: '8'
    required: false

  pnpm-args:
    description: 'Arguments to use with pnpm install'
    default: '--frozen-lockfile'
    required: false

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - uses: pnpm/action-setup@v3
      with:
        version: ${{ inputs.pnpm-version }}
        run_install: false

    - name: Get pnpm store directory
      id: store
      shell: bash
      run: |
        echo "store-path=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v4
      name: Setup pnpm cache
      with:
        path: ${{ steps.store.outputs.store-path }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: pnpm install
