name: 'Rebase'
description: 'Rebase and update one branch with another.'

inputs:
  target:
    description: 'Target branch you wish to update.'
    required: true

  source:
    description: 'Source branch to use to rebase target.'
    required: true

  token:
    description: 'GitHub token with push access.'
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ inputs.token }}
        ref: ${{ inputs.target }}
        fetch-depth: 0

    - uses: edielemoine/npm-releaser-action/setup-git-credentials@main

    - name: 'Rebase and push'
      if: inputs.target && inputs.base
      shell: bash
      run: |
        git config --list
        git rebase "origin/${{ inputs.base }}"
        git push
