name: '🔸 Build image'

on:
  workflow_call:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v2

      - name: 'Build'
        uses: docker/build-push-action@v3
        with:
          tags: edielemoine/npm-releaser-action:latest
          target: 'test'
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
