name: '🔸 Yarn install - Cache'

on:
  workflow_call:

jobs:
  install:
    name: 'Install'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: myparcelnl/actions/composer-install@v3
