on:
  workflow_call:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: edielemoine/nra

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: edielemoine/npm-releaser-action/build-docker-gcr@main
        id: build
        with:
          image: edielemoine/nra
          target: test
          registry-user: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          docker run ${{ steps.build.outputs.tagged-image }}

      - name: 'Get coverage file from container'
        run: docker cp $(docker ps -alq):/app/clover.xml .

      - name: 'Read file'
        run: cat clover.xml
