name: '🔸 Docker build - Original'

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: myparcelnl/actions/build-docker-image@v3
        id: docker
        with:
          image: edielemoine/nra-original
          key: myparcel-nra-original
