name: '🔸 Docker Buildx'

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: 'Prepare'
        id: prepare
        run: |
          TAG="buildx"
          IMAGE="edielemoine/nra"
          echo "tagged_image=${IMAGE}:${TAG}" >> $GITHUB_OUTPUT
          echo "tag=${TAG}" >> $GITHUB_OUTPUT

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v2

#      - name: 'Cache Docker layers'
#        uses: actions/cache@v3
#        with:
#          path: /tmp/.buildx-cache
#          key: ${{ runner.os }}-buildx-${{ hashFiles('Dockerfile') }}-${{ hashFiles('**/composer.lock') }}
#          restore-keys: |
#            ${{ runner.os }}-buildx-${{ hashFiles('Dockerfile') }}
#            ${{ runner.os }}-buildx

      - name: 'Build Docker image'
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ${{ steps.prepare.outputs.tagged_image }}
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

#      - name: Move cache
#        run: |
#          rm -rf /tmp/.buildx-cache
#          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
