on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: 'Prepare'
        id: prepare
        run: |
          TAG="buildx-$(echo $GITHUB_SHA | head -c7)"
          IMAGE="edielemoine/nra"
          echo ::set-output name=tagged_image::${IMAGE}:${TAG}
          echo ::set-output name=tag::${TAG}

      - name: 'Set up Docker Buildx'
        id: buildx
        uses: docker/setup-buildx-action@v2

#      - name: 'Cache Docker layers'
#        uses: actions/cache@v2
#        with:
#          path: /tmp/.buildx-cache
#          key: ${{ runner.os }}-buildx-${{ hashFiles('Dockerfile') }}-${{ hashFiles('**/composer.lock') }}
#          restore-keys: |
#            ${{ runner.os }}-buildx-${{ hashFiles('Dockerfile') }}
#            ${{ runner.os }}-buildx

      - name: 'Build Docker image'
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ steps.prepare.outputs.tagged_image }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

#      - name: Move cache
#        run: |
#          rm -rf /tmp/.buildx-cache
#          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
