name: '♻️ Rebase'

on:
  workflow_call:
    inputs:
      base:
        required: true
        type: string
      target:
        required: true
        type: string

    secrets:
      GH_REPO_TOKEN:
        required: true

jobs:
  rebase:
    name: 'Rebase branches'
    runs-on: ubuntu-20.04
    steps:
      - run: |
          export GITHUB_TOKEN=${{ secrets.GH_REPO_TOKEN }}
          echo $GITHUB_TOKEN
          echo ${{ secrets.GH_REPO_TOKEN }}

      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.target }}
          fetch-depth: 0
          persist-credentials: false

      - uses: oleksiyrudenko/gha-git-credentials@v2.1
        with:
          global: true
          name: 'MyParcelBot'
          email: 'edie+bot@myparcel.nl'
          actor: 'MyParcelBot'

      - name: 'Rebase and push'
        if: inputs.target && inputs.base
        run: |
          git rebase "origin/${{ inputs.base }}"
          git push
