name: '🔸 Release'

on:
  workflow_call:
    inputs:
      setup_php:
        description: 'An optional php version to set up before running the release.'
        type: string
        default: '0'
        required: false

      pre_release_cmd:
        description: 'A command to run after installing everything, but before releasing.'
        type: string
        default: '0'
        required: false

    secrets:
      GH_REPO_TOKEN:
        description: 'Required for pushing commits to git.'
        required: false

      NPM_TOKEN:
        description: 'Required for publishing to NPM.'
        required: false

jobs:
  release:
    name: 'Release'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - if: ${{ inputs.setup_php != '0' }}
        uses: myparcelnl/actions/composer-install@v1
        with:
          php-version: ${{ inputs.setup_php }}

      - uses: myparcelnl/actions/yarn-install@v1

      - if: ${{ inputs.pre_release_cmd != '0' }}
        run: ${{ inputs.pre_release_cmd }}

      - uses: edielemoine/npm-releaser-action/setup-git-credentials@main
        with:
          token: ${{ secrets.GH_REPO_TOKEN }}

      - uses: myparcelnl/actions/semantic-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
