name: '♻️ Rebase'

on:
  workflow_call:
    inputs:
      base:
        required: true
        type: string
      target:
        required: true
        type: string

    secrets:
      GH_REPO_TOKEN:
        required: true

jobs:
  rebase:
    name: 'Rebase branches'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_REPO_TOKEN }}
          ref: ${{ inputs.target }}
          fetch-depth: 0

      - uses: oleksiyrudenko/gha-git-credentials@v2.1
        with:
          token: ${{ secrets.GH_REPO_TOKEN }}
          name: 'MyParcelBot'
          email: 'edie+bot@myparcel.nl'
          actor: 'MyParcelBot'

      - name: 'Rebase and push'
        if: inputs.target && inputs.base
        run: |
          git config --list
          git rebase "origin/${{ inputs.base }}"
          git push
