name: '♻️ Run tests 🧪'

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: false
        default: ''
        description: 'Git ref to run on.'

      image_name:
        type: string
        required: true

      image_key:
        type: string
        required: false

      docker_args:
        type: string
        required: false
        default: '--target test'

      release:
        type: boolean
        required: false
        default: false

      environment:
        type: string
        required: false
        default: ''

jobs:
  test:
    name: 'Run tests'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.ref }}
          persist-credentials: false

      - uses: myparcelnl/actions/build-docker-image@v1
        id: docker
        with:
          image: ${{ inputs.image_name }}
          key: ${{ inputs.image_key || inputs.image_name }}
          docker_args: ${{ inputs.docker_args }}

      - name: 'Create .env file'
        run: |
          cat << EOF > .env
          ${{ inputs.environment }}
          EOF

      - name: 'Run tests'
        run: docker run --env-file .env ${{ steps.docker.outputs.tagged_image }}

      - name: 'Get coverage file from container'
        run: docker cp $(docker ps -alq):/app/coverage.xml .

      - uses: myparcelnl/actions/update-coverage@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: 'Trigger release'
        if: inputs.release
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_REPO_TOKEN }}
          event-type: release
