name: '🔸 Run tests'

on:
  workflow_call:
    inputs:
      ref:
        description: 'Git ref to run on.'
        type: string
        required: false
        default: ''

      image_name:
        description: 'Docker image name.'
        type: string
        required: true

      image_key:
        description: 'Image cache key.'
        type: string
        required: false

      docker_args:
        description: 'Arguments to pass to docker build.'
        type: string
        required: false
        default: '--target test'

      environment:
        description: 'Content to pass to docker via .env file.'
        type: string
        required: false
        default: ''

    secrets:
      CODECOV_TOKEN:
        description: 'Token for pushing coverage results to codecov.'
        required: false

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.ref }}
          persist-credentials: false

      - name: 'Create .env file'
        run: |
          cat << EOF > .env
          ${{ inputs.environment }}
          EOF

      - uses: myparcelnl/actions/build-docker-image@v1
        id: docker
        with:
          image: ${{ inputs.image_name }}
          key: ${{ inputs.image_key || inputs.image_name }}
          docker_args: ${{ inputs.docker_args }}

      - name: 'Run Dockerfile'
        run: docker run --env-file .env ${{ steps.docker.outputs.tagged_image }}

      - name: 'Get coverage file from container'
        run: docker cp $(docker ps -alq):/app/coverage.xml .

      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage.xml
          retention-days: 14

  coverage:
    name: 'Update coverage'
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: coverage

      - uses: myparcelnl/actions/update-coverage@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
