name: '🔸 Yarn install - Cache setup-node'

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node version to use'
        type: string
        default: '20'
        required: false

jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: ./yarn-install-cache-setup-node
        with:
          node-version: ${{ inputs.node-version }}
