name: '🔸 Yarn install - Cache both'

on:
  workflow_call:

jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-cache-both-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-cache-both-

      - run: yarn install
        shell: bash
