name: '🔸 Yarn install - Cache node modules'

on:
  workflow_call:
    inputs:
      cache-key:
        description: 'Cache key to use'
        type: string
        default: ''
        required: false

jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ inputs.cache-key }}-${{ runner.os }}-yarn-node-modules-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ inputs.cache-key }}-${{ runner.os }}-yarn-node-modules-

      - run: yarn install
        shell: bash
