name: '🔸 Yarn install - Cache both'

on:
  workflow_call:
    inputs:
      cache-key:
        description: 'Cache key to use'
        type: string
        default: ''
        required: false

      node-version:
        description: 'Node.js version to use'
        type: string
        default: '20'
        required: false

jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: ./yarn-install-cache-both
        with:
          cache-key: ${{ github.event.inputs.cache-key }}
          node-version: ${{ github.event.inputs.node-version }}
