name: 'Bypass protections'

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: myparcelnl/actions/setup-git-credentials@v3
        id: credentials
        with:
          app-id: ${{ secrets.BOOPS_BOOPS_APP_ID }}
          private-key: ${{ secrets.BOOPS_BOOPS_PRIVATE_KEY }}

      - run: |
          echo "fix: test $(date)" >> CHANGELOG.md

          git add CHANGELOG.md

          git commit -m "fix: test"

          git push
