name: 'Bypass protections'

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: ./create-checks
        with:
          checks: codecov/patch,codecov/project

      - uses: ./create-checks
        with:
          checks: |
            codecov/patch2
            codecov/project2
