name: 'Bypass protections'

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/github-script@v6
        name: 'Create fake check runs'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: { required_status_checks: requiredStatusChecks } } = await github.rest.repos.getBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: context.ref,
            });
            
            const checkNames = requiredStatusChecks.contexts.map(check => check.name);
            core.info(`Required checks: ${checkNames.join(', ')}`);

            await Promise.all(checkNames.map(async name => {
              core.info(`Creating check: ${name}`);
              await github.rest.checks.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                head_sha: context.sha,
                name,
                status: 'completed'
                conclusion: 'success',                
              });
            }));
