on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-22.04
    name: 'Check difference between branches'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Check for difference'
        id: check
        run: |
          git rev-list --count --exit-code origin/main..origin/develop

          if [ $? -eq 0 ]; then
            echo "::set-output name=diff::false"
          fi

          echo "::set-output name=diff::true"

          echo "There are differences between main and develop" >> $GITHUB_STEP_SUMMARY
          echo "The following commits are not in develop:" >> $GITHUB_STEP_SUMMARY
          git log --pretty=format:'%s' origin/main..origin/develop | grep -E '^(feat|fix|revert)(\(.+\))?: .{1,50}' >> $GITHUB_STEP_SUMMARY
