name: 'Rebase pull request'

on:
  repository_dispatch:
    types: [ rebase-command ]

jobs:
  rebase:
    uses: edielemoine/npm-releaser-action/.github/workflows/--rebase-pull-request.yml@main
    with:
      head: ${{ github.event.client_payload.pull_request.head.label }}
