name: 'Rebase pull request'

on:
  repository_dispatch:
    types: [ rebase-command ]

jobs:
  rebase:
    uses: ./.github/workflows/--rebase-pull-request.yml
    with:
      head: ${{ github.event.client_payload.pull_request.head.label }}
