name: 'authorize bot'

on:
  repository_dispatch:
    types: [comment-command]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: token
        with:
          app-id: ${{ secrets.BOOPS_BOOPS_APP_ID }}
          private-key: ${{ secrets.BOOPS_BOOPS_PRIVATE_KEY }}

      - name: 'Comment on pull request'
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          token: ${{ steps.token.outputs.token }}
          body: |
            :robot:: Beep boop! I'm a bot. Supposedly I'm authorized to do this, but I'm not sure. I'll try anyway. 

            app slug: ${{ steps.token.outputs.app-slug }}[bot]
            installation id: ${{ steps.token.outputs.installation-id }}
