name: 'Dispatch command 📡'

on:
  issue_comment:
    types: [created]

jobs:
  dispatch:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/create-github-app-token@v1
        id: token
        with:
          app-id: ${{ secrets.BOOPS_BOOPS_APP_ID }}
          private-key: ${{ secrets.BOOPS_BOOPS_PRIVATE_KEY }}

      - uses: peter-evans/slash-command-dispatch@v4
        with:
          token: ${{ steps.token.outputs.token }}
          permission: write
          issue-type: pull-request
          commands: |
            comment
            rebase
            test
