name: 'Dispatch command 📡'

on:
  issue_comment:
    types: [created]

jobs:
  dispatch:
    runs-on: ubuntu-22.04
    steps:
      - uses: peter-evans/slash-command-dispatch@v4
        with:
          token: ${{ github.token }}
          permission: write
          issue-type: pull-request
          commands: |
            comment
            rebase
            test
