name: 'Dispatch command'

on:
  issue_comment:
    types: [ created ]

jobs:
  dispatch:
    uses: edielemoine/npm-releaser-action/.github/workflows/--dispatch.yml@main
    with:
      secrets: inherit
      commands: |
        rebase
        python
