name: 'Dispatch command 📡'

on:
  issue_comment:
    types: [created]

jobs:
  dispatch:
    uses: ./.github/workflows/--dispatch.yml
    secrets: inherit
    with:
      commands: rebase test comment
      token: ${{ github.token }}
