name: 'Do action'

on:
  repository_dispatch:
    types: [ do-action ]

jobs:
  trigger:
    name: 'Release'
    runs-on: ubuntu-latest

    steps:
      - run: echo ${{ github }}
      - run: echo ${{ inputs }}
      - run: echo ${{ job }}
      - run: echo ${{ github }}
