name: 'Parse issue'

on:
  issues:
    types:
      - edited
      - opened
      - reopened

jobs:
  label:
    runs-on: ubuntu-22.04
    steps:
      - name: Issue Forms Body Parser
        id: parse
        uses: zentered/issue-forms-body-parser@v1.4.3

      - run: echo "${{ JSON.stringify(steps.parse.outputs.data) }}"
