name: Pull Request
on: [ pull_request ]
jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - run: node_modules/eslint/bin/eslint.js .

      - name: Lint
        uses: Krizzu/eslint-check-action@v1.1.0
        with:
          ghToken: ${{ secrets.GITHUB_TOKEN }}

