name: 'Pull request'

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  assign-author:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: ./pr-assign-author
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./pr-assign-author
        continue-on-error: true
        with:
          app-id: ${{ secrets.BOOPS_BOOPS_APP_ID }}
          private-key: ${{ secrets.BOOPS_BOOPS_PRIVATE_KEY }}

  validate-title:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: ./pr-validate-title-conventional
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./pr-validate-title-conventional
        continue-on-error: true
        with:
          app-id: ${{ secrets.BOOPS_BOOPS_APP_ID }}
          private-key: ${{ secrets.BOOPS_BOOPS_PRIVATE_KEY }}
