name: 'On pull request open'

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  #  assign-author:
  #    runs-on: ubuntu-22.04
  #    steps:
  #      - uses: actions/checkout@v4
  #
  #      - uses: ./pr-assign-author
  #        continue-on-error: true
  #        with:
  #          github-token: ${{ secrets.GITHUB_TOKEN }}
  #
  #      - uses: ./pr-assign-author
  #        continue-on-error: true
  #        with:
  #          app-id: ${{ secrets.BOOPS_BOOPS_APP_ID }}
  #          private-key: ${{ secrets.BOOPS_BOOPS_PRIVATE_KEY }}
  #
  #  validate-title:
  #    runs-on: ubuntu-22.04
  #    steps:
  #      - uses: actions/checkout@v4
  #
  #      - uses: ./pr-validate-title-conventional
  #        continue-on-error: true
  #        with:
  #          github-token: ${{ secrets.GITHUB_TOKEN }}
  #
  #      - uses: ./pr-validate-title-conventional
  #        continue-on-error: true
  #        with:
  #          app-id: ${{ secrets.BOOPS_BOOPS_APP_ID }}
  #          private-key: ${{ secrets.BOOPS_BOOPS_PRIVATE_KEY }}

  #  assign-author:
  #    if: github.event.action == 'opened'
  #    runs-on: ubuntu-22.04
  #    steps:
  #      - uses: myparcelnl/actions/pr-assign-author@v3
  #        with:
  #          token: ${{ secrets.GITHUB_TOKEN }}

  post-comment:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: 'Create summary'
        id: summary
        shell: bash
        #language=bash
        run: |
          echo "## _My Summary_"   >> $GITHUB_STEP_SUMMARY
          echo ""                  >> $GITHUB_STEP_SUMMARY
          echo "This is a summary" >> $GITHUB_STEP_SUMMARY
          echo "that was made in"  >> $GITHUB_STEP_SUMMARY
          echo "GitHub Actions."   >> $GITHUB_STEP_SUMMARY

          echo 'summary<<EOF'      >> $GITHUB_OUTPUT
          cat $GITHUB_STEP_SUMMARY >> $GITHUB_OUTPUT
          echo 'EOF'               >> $GITHUB_OUTPUT

      - uses: ./update-comment
        with:
          app-id: ${{ secrets.BOOPS_BOOPS_APP_ID }}
          private-key: ${{ secrets.BOOPS_BOOPS_PRIVATE_KEY }}
          issue-number: ${{ github.event.pull_request.number }}
          identifier: 'random-comment-1'
          body: |-
            This is a random comment that was made in github actions. 

            Run id: ${{ github.run_id }}

      - uses: ./update-comment
        with:
          app-id: ${{ secrets.BOOPS_BOOPS_APP_ID }}
          private-key: ${{ secrets.BOOPS_BOOPS_PRIVATE_KEY }}
          issue-number: ${{ github.event.pull_request.number }}
          identifier: 'summary'
          body: |-
            ${{ steps.summary.outputs.summary }}

            <details>
            <summary>Details</summary>

            run_id:            ${{ github.run_id }}
            action_status:     ${{ github.action }}
            action_status:     ${{ github.action_status }}
            action_ref:        ${{ github.action_ref }}
            action_path:       ${{ github.action_path }}
            action_repository: ${{ github.action_repository }}

            </details>

      - uses: ./update-comment
        with:
          app-id: ${{ secrets.BOOPS_BOOPS_APP_ID }}
          private-key: ${{ secrets.BOOPS_BOOPS_PRIVATE_KEY }}
          issue-number: ${{ github.event.pull_request.number }}
          identifier: 'random-comment-2'
          body: |-
            This is another random comment that was made in github actions. 

            Run id: ${{ github.run_id }}
