name: 'On pull request open'

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  #  assign-author:
  #    runs-on: ubuntu-22.04
  #    steps:
  #      - uses: actions/checkout@v4
  #
  #      - uses: ./pr-assign-author
  #        continue-on-error: true
  #        with:
  #          github-token: ${{ secrets.GITHUB_TOKEN }}
  #
  #      - uses: ./pr-assign-author
  #        continue-on-error: true
  #        with:
  #          app-id: ${{ secrets.BOOPS_BOOPS_APP_ID }}
  #          private-key: ${{ secrets.BOOPS_BOOPS_PRIVATE_KEY }}
  #
  #  validate-title:
  #    runs-on: ubuntu-22.04
  #    steps:
  #      - uses: actions/checkout@v4
  #
  #      - uses: ./pr-validate-title-conventional
  #        continue-on-error: true
  #        with:
  #          github-token: ${{ secrets.GITHUB_TOKEN }}
  #
  #      - uses: ./pr-validate-title-conventional
  #        continue-on-error: true
  #        with:
  #          app-id: ${{ secrets.BOOPS_BOOPS_APP_ID }}
  #          private-key: ${{ secrets.BOOPS_BOOPS_PRIVATE_KEY }}

  #  assign-author:
  #    if: github.event.action == 'opened'
  #    runs-on: ubuntu-22.04
  #    steps:
  #      - uses: myparcelnl/actions/pr-assign-author@v3
  #        with:
  #          token: ${{ secrets.GITHUB_TOKEN }}

  post-comment:
    runs-on: ubuntu-22.04
    steps:
      - uses: myparcelnl/actions/setup-app-credentials@v4
        id: credentials
        with:
          app-id: ${{ secrets.BOOPS_BOOPS_APP_ID }}
          private-key: ${{ secrets.BOOPS_BOOPS_PRIVATE_KEY }}

      - name: 'Create summary'
        id: summary
        shell: bash
        #language=bash
        run: |
          echo "## _My Summary_"   >> $GITHUB_STEP_SUMMARY
          echo ""                  >> $GITHUB_STEP_SUMMARY
          echo "This is a summary" >> $GITHUB_STEP_SUMMARY
          echo "that was made in"  >> $GITHUB_STEP_SUMMARY
          echo "GitHub Actions."   >> $GITHUB_STEP_SUMMARY

          # put multiline output into variable
          echo "summary=<<EOF" >> $GITHUB_OUTPUT
          cat $GITHUB_STEP_SUMMARY >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      #      - name: 'Create summary'
      #        shell: bash
      #        id: summary
      #        #language=bash
      #        run: |
      #          {
      #            echo 'summary=<<EOF'
      #            # My Summary
      #
      #            This is a summary that was made in GitHub Actions.
      #
      #            echo EOF
      #          } >> $GITHUB_OUTPUT

      - uses: peter-evans/find-comment@v3
        id: find-comment-1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: ${{ steps.credentials.outputs.git-name }}
          body-includes: 'a random'

      - uses: peter-evans/find-comment@v3
        id: find-comment-2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: ${{ steps.credentials.outputs.git-name }}
          body-includes: 'pr-post-summary'

      - uses: peter-evans/find-comment@v3
        id: find-comment-3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: ${{ steps.credentials.outputs.git-name }}
          body-includes: 'another random'

      - name: 'Create or update other random comment'
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ steps.credentials.outputs.token }}
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.find-comment-1.outputs.comment-id }}
          edit-mode: replace
          body: |-
            This is a random comment that was made in github actions. Run id: ${{ github.run_id }}

      - name: 'Create or update comment with summary'
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ steps.credentials.outputs.token }}
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.find-comment-2.outputs.comment-id }}
          edit-mode: replace
          body: |-
            ${{ steps.summary.outputs.summary }}

            Run id: ${{ github.run_id }}

            <!-- pr-post-summary -->

      - name: 'Create or update other random comment'
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ steps.credentials.outputs.token }}
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.find-comment-3.outputs.comment-id }}
          edit-mode: replace
          body: |-
            This is another random comment that was made in github actions. Run id: ${{ github.run_id }}
