name: 'Pull request'

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

env:
  GITHUB_APP_ID: ${{ secrets.BOOPS_BOOPS_APP_ID }}
  GITHUB_PRIVATE_KEY: ${{ secrets.BOOPS_BOOPS_PRIVATE_KEY }}

jobs:
  assign-author:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: ./pr-assign-author

  validate-title:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: ./pr-validate-title-conventional
        with:
          app-id: ${{ secrets.BOOPS_BOOPS_APP_ID }}
          private-key: ${{ secrets.BOOPS_BOOPS_PRIVATE_KEY }}
