name: 'Python script'

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or commit'
        required: true
        type: string

  repository_dispatch:
    types: [ python-command ]

jobs:
  release:
    name: 'Run Python script'
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo ${{ github.event.client_payload.pull_request.head.label }}
        shell: bash

      - run: |
          ref = "${{ github.event.client_payload.pull_request.head.label }}" or "${{ github.event.inputs.ref }})" or "main <fallback>"
          print(ref)
          print("::set-output name=ref::{ref}")
        shell: python
        name: python

      - run: |
          echo ${{ github.steps.python.outputs.ref }} 
