name: 'Script'

on:
  push:
    branches:
      - on-run-script

  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or commit'
        required: true
        type: string

  repository_dispatch:
    types: [ python-command ]

jobs:
  release:
    name: 'Run script'
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo ${{  github.event.client_payload.pull_request.head.label || github.event.inputs.ref || 'main' }}
        shell: bash
