name: 'Rebase'

on:
  repository_dispatch:
    types: [ rebase ]

  workflow_dispatch:
    inputs:
      source:
        type: choice
        description: 'Source'
        default: 'develop'
        required: false
        options:
          - main
          - develop
      target:
        type: choice
        description: 'Target'
        default: 'main'
        required: false
        options:
          - main
          - develop

jobs:
  rebase:
    uses: edielemoine/npm-releaser-action/.github/workflows/rebase.yml@main
    with:
      source: ${{ github.event.client_payload.source || github.event.inputs.source }}
      target: ${{ github.event.client_payload.target || github.event.inputs.target }}
    secrets:
      inherit: true
