name: Rebase pull request

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  rebase-master:
    name: Rebase base branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_ADMIN_TOKEN }}
          fetch-depth: 0
      - name: Rebase
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git rebase origin/${GITHUB_BASE_REF}
          git push origin HEAD:${GITHUB_REF#refs/heads/} -f
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
