name: Rebase pull request

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  rebase-master:
    name: Rebase master
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_ADMIN_TOKEN }}
          fetch-depth: 0
      - name: Rebase master
        run: |
          git rebase origin/master
          git push -f
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}

  rebase-develop:
    name: Rebase develop
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_ADMIN_TOKEN }}
          fetch-depth: 0
      - name: Rebase master
        run: |
          git rebase origin/develop
          git push -f
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
