name: 'Release'

on:
  repository_dispatch:
    types: [ release-command ]

jobs:
  release:
    name: 'Release'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: 'Merge develop into main'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git fetch origin main
          git fetch origin develop

          git rebase origin/develop
          git push
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
