name: Release

on:
  push:
    branches:
      - master
      - main

jobs:
  release:
    name: Semantic release
    runs-on: ubuntu-latest
    if: "!contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
      - name: Checkout 📦
        uses: actions/checkout@v2

      - uses: myparcelnl/actions/yarn-install@v1

      - name: Release 🚀
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GH_ADMIN_TOKEN}}
