name: 'Run Yarn tests'

on:
  workflow_dispatch:

jobs:
  test-yarn:
    name: 'Run yarn tests 🧪'
    uses: edielemoine/npm-releaser-action/.github/workflows/--run-tests-yarn.yml@main
    secrets: inherit
