name: 'Merge develop into main'

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      release:
        description: 'Trigger release (Only on main)'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  release:
    name: 'Rebase develop onto main'
    runs-on: ubuntu-latest

    steps:
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2
        with:
          ref: main

      - if: ${{ github.events.inputs.release }}
        run: |
          echo "Triggering release!"


      - run: |
          echo ${{ github.event.inputs.toggle }}
          echo ${{ github.event.inputs.toggle }} && '-f' 

      - name: 'Rebase main onto develop'
        run: |
          git fetch origin main
          git fetch origin develop

          git rebase origin/develop
          git push

      - name: 'Rebase develop onto main'
        run: |
          git fetch origin main
          git fetch origin develop

          git checkout develop
          git rebase origin/main
          git push
