name: 'Merge develop into main'

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      release:
        description: 'Trigger release (Only on main)'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  release:
    name: 'Rebase develop onto main'
    runs-on: ubuntu-latest

    steps:
      - if: ${{ github.events.inputs.release }}
        run: |
          echo "Triggering release!"

      - uses: actions/checkout@v2
        with:
          ref: main

      - name: 'Rebase'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git fetch origin main
          git fetch origin develop

          git rebase origin/develop
          git push
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
