name: 'Test yarn cache speeds'

on:
  workflow_dispatch:

concurrency:
  group: test-yarn-cache-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ###
  # current
  ###
  current-cold:
    uses: ./.github/workflows/--yarn-install-current.yml
    with:
      cache-key: ${{ github.sha }}

  current-warm:
    needs: current-cold
    uses: ./.github/workflows/--yarn-install-current.yml
    with:
      cache-key: ${{ github.sha }}

  ###
  # setup-node
  ###
  setup-node-cold:
    uses: ./.github/workflows/--yarn-install-setup-node.yml

  setup-node-warm:
    needs: setup-node-cold
    uses: ./.github/workflows/--yarn-install-setup-node.yml

  ###
  # cache-node-modules
  ###
  cache-node-modules-cold:
    uses: ./.github/workflows/--yarn-install-cache-node-modules.yml
    with:
      cache-key: ${{ github.sha }}

  cache-node-modules-warm:
    needs: cache-node-modules-cold
    uses: ./.github/workflows/--yarn-install-cache-node-modules.yml
    with:
      cache-key: ${{ github.sha }}

  ###
  # cache-both
  ###
  cache-both-cold:
    uses: ./.github/workflows/--yarn-install-cache-both.yml
    with:
      cache-key: ${{ github.sha }}

  cache-both-warm:
    needs: cache-both-cold
    uses: ./.github/workflows/--yarn-install-cache-both.yml
    with:
      cache-key: ${{ github.sha }}

  ###
  # cache-folder
  ###
  cache-folder-cold:
    uses: ./.github/workflows/--yarn-install-cache-folder.yml
    with:
      cache-key: ${{ github.sha }}

  cache-folder-warm:
    needs: cache-folder-cold
    uses: ./.github/workflows/--yarn-install-cache-folder.yml
    with:
      cache-key: ${{ github.sha }}

  ###
  # gist
  ###
  gist-cold:
    uses: ./.github/workflows/--yarn-install-gist.yml
    with:
      cache-key: ${{ github.sha }}

  gist-warm:
    needs: gist-cold
    uses: ./.github/workflows/--yarn-install-gist.yml
    with:
      cache-key: ${{ github.sha }}
