name: 'Test yarn cache speeds'

on:
  workflow_dispatch:

concurrency:
  group: test-yarn-cache-${{ github.ref }}
  cancel-in-progress: true

jobs:
  original-1:
    uses: ./.github/workflows/--yarn-install-original.yml
  original-2:
    needs: original-1
    uses: ./.github/workflows/--yarn-install-original.yml

  cache-1:
    uses: ./.github/workflows/--yarn-install-cache.yml
  cache-2:
    needs: cache-1
    uses: ./.github/workflows/--yarn-install-cache.yml

  node_modules-1:
    uses: ./.github/workflows/--yarn-install-node-modules.yml
  node_modules-2:
    needs: node_modules-1
    uses: ./.github/workflows/--yarn-install-node-modules.yml

  both-1:
    uses: ./.github/workflows/--yarn-install-both.yml
  both-2:
    needs: both-1
    uses: ./.github/workflows/--yarn-install-both.yml

  manual-1:
    uses: ./.github/workflows/--yarn-install-cache-manual.yml
  manual-2:
    needs: manual-1
    uses: ./.github/workflows/--yarn-install-cache-manual.yml
