name: All in one job

on:
  pull_request: ~
  push:
    branches:
      - master

jobs:
  everything:
    name: Do everything
    runs-on: ubuntu-latest
    env:
      SHOULD_RELEASE: ${{ github.event_name == 'push' }}
    steps:
      - name: Create
        run: |
          echo "Pretending to prepare files"
          touch file.txt
          echo "file content" >> file.txt
          echo "$SHOULD_RELEASE"

      - name: Check
        run: |
          echo "Pretending to run test"
          cat file.txt

      - name: Run semantic release
        if: ${{ env.SHOULD_RELEASE == true }}
        run: echo "Pretending to run semantic release"
