name: 'Test docker build speeds'

on:
  workflow_dispatch:

jobs:
#  none-1:
#    uses: ./.github/workflows/--docker-build-no-cache.yml
#  none-2:
#    needs: none-1
#    uses: ./.github/workflows/--docker-build-no-cache.yml
#
#  original-1:
#    uses: ./.github/workflows/--docker-build-original.yml
#  original-2:
#    needs: original-1
#    uses: ./.github/workflows/--docker-build-original.yml

#  buildx-1:
#    uses: ./.github/workflows/--docker-buildx.yml
#  buildx-2:
#    needs: buildx-1
#    uses: ./.github/workflows/--docker-buildx.yml
#
#  buildx-local-1:
#    uses: ./.github/workflows/--docker-buildx-local.yml
#  buildx-local-2:
#    needs: buildx-local-1
#    uses: ./.github/workflows/--docker-buildx-local.yml

  build-gpr-1:
    uses: ./.github/workflows/--docker-build-gpr.yml
  build-gpr-2:
    needs: build-gpr-1
    uses: ./.github/workflows/--docker-build-gpr.yml
