name: 'Run tests 🧪'

on:
  workflow_call:
    inputs:
      ref:
        description: 'Branch to run on'
        type: string
        default: ''
        required: false

    secrets:
      CODECOV_TOKEN:
        description: 'Token for pushing coverage results to codecov.'
        required: false

  repository_dispatch:
    types: [ test ]

  workflow_dispatch:

jobs:
  test-docker:
    uses: edielemoine/npm-releaser-action/.github/workflows/--run-tests-docker.yml@main
    secrets: inherit
    with:
      image_name: myparcel/sdk-test
      image_key: php-sdk-test
      ref: ${{ inputs.ref || github.event.inputs.ref || github.event.client_payload.pull_request.head.label || '' }}
      environment: |
        CI=${CI}
        API_KEY_NL=API_KEY_NL
        API_KEY_BE=API_KEY_BE

  test-yarn:
    uses: edielemoine/npm-releaser-action/.github/workflows/--run-tests-yarn.yml@main
    secrets: inherit
    with:
      ref: ${{ inputs.ref || github.event.inputs.ref || github.event.client_payload.pull_request.head.label || '' }}
