name: 'Test yarn cache speeds'

on:
  workflow_dispatch:

concurrency:
  group: test-yarn-cache-${{ github.ref }}
  cancel-in-progress: true

jobs:
  original-1:
    uses: ./.github/workflows/--yarn-install-original.yml
  original-2:
    needs: original-1
    uses: ./.github/workflows/--yarn-install-original.yml

  setup-node-1:
    uses: ./.github/workflows/--yarn-install-setup-node.yml
  setup-node-2:
    needs: setup-node-1
    uses: ./.github/workflows/--yarn-install-setup-node.yml

  node-modules-1:
    uses: ./.github/workflows/--yarn-install-cache-node-modules.yml
  node-modules-2:
    needs: node-modules-1
    uses: ./.github/workflows/--yarn-install-cache-node-modules.yml

  both-1:
    uses: ./.github/workflows/--yarn-install-cache-both.yml
  both-2:
    needs: both-1
    uses: ./.github/workflows/--yarn-install-cache-both.yml

  cache-folder-1:
    uses: ./.github/workflows/--yarn-install-cache-folder.yml
  cache-folder-2:
    needs: cache-folder-1
    uses: ./.github/workflows/--yarn-install-cache-folder.yml

  gist-1:
    uses: ./.github/workflows/--yarn-install-gist.yml
  gist-2:
    needs: gist-1
    uses: ./.github/workflows/--yarn-install-gist.yml
