name: 'Test docker build speeds'

on:
  workflow_dispatch:

jobs:
#  none-1:
#    uses: edielemoine/npm-releaser-action/.github/workflows/--docker-build-no-cache.yml@main
#  none-2:
#    needs: none-1
#    uses: edielemoine/npm-releaser-action/.github/workflows/--docker-build-no-cache.yml@main
#
#  original-1:
#    uses: edielemoine/npm-releaser-action/.github/workflows/--docker-build-original.yml@main
#  original-2:
#    needs: original-1
#    uses: edielemoine/npm-releaser-action/.github/workflows/--docker-build-original.yml@main

  buildx-1:
    uses: edielemoine/npm-releaser-action/.github/workflows/--docker-buildx.yml@main
  buildx-2:
    needs: buildx-1
    uses: edielemoine/npm-releaser-action/.github/workflows/--docker-buildx.yml@main

  buildx-local-1:
    uses: edielemoine/npm-releaser-action/.github/workflows/--docker-buildx-local.yml@main
  buildx-local-2:
    needs: buildx-local-1
    uses: edielemoine/npm-releaser-action/.github/workflows/--docker-buildx-local.yml@main

  build-gpr-1:
    uses: edielemoine/npm-releaser-action/.github/workflows/--docker-build-gpr.yml@main
  build-gpr-2:
    needs: build-gpr-1
    uses: edielemoine/npm-releaser-action/.github/workflows/--docker-build-gpr.yml@main
