name: 'Test outputs'

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: ./test-outputs
        id: test
        with:
          test: 'test'

      - name: 'Test'
        shell: bash
        run: |
          echo ${{ steps.test.outputs.test }}
