name: Separate jobs

on:
  pull_request: ~
  push:
    branches:
      - master

env:
  shouldRelease: ${{ github.event_name == 'push' }}

jobs:
  prepare:
    name: Prepare files
    runs-on: ubuntu-latest
    steps:
      - name: Create
        run: |
          echo "Pretending to prepare files"
          touch file.txt
          echo "file content" >> file.txt

  test:
    name: Test and update coverage
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Check
        run: |
          echo "Pretending to run test"
          cat file.txt

  publish:
    name: Run semantic release
    if: env.shouldRelease
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Run semantic release
        run: echo "Pretending to run semantic release"
