name: 'Test outputs'

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: ./test-outputs
        id: test
        with:
          test: 'test'

      - name: 'Test'
        shell: bash
        run: |
          echo ${{ steps.test.outputs.test }}

      - name: md5 hash
        id: md5
        shell: bash
        run: |
          echo "$(echo -n 'ghcr.io/myparcelnl/php-xd:7.4' | md5sum | cut -d ' ' -f 1)"
          echo "$(echo -n 'ghcr.io/myparcelnl/php-xd:7.4' | md5sum | cut -d ' ' -f 1)"
          echo "$(echo -n 'ghcr.io/myparcelnl/php-xd:7.4' | md5sum | cut -d ' ' -f 1)"
          echo "$(echo -n 'ghcr.io/myparcelnl/php-xd:7.4' | md5sum | cut -d ' ' -f 1)"
