name: 'Run phpunit tests'

on:
  workflow_dispatch:

  pull_request:
    paths:
      - '**/*.php'

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: myparcelnl/actions/composer-install@v3

      - run: |
          vendor/bin/phpunit
        shell: bash

      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: build/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: 'Deploy Allure report to Github Pages'
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

      - name: 'Get GitHub Pages URL'
        id: get-url
        run: |
          ::set-output=url=https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ github.run_number }}

      - name: 'Post the link to the report'
        if: always() && github.event.pull_request
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Test report'
          state: 'success'
          sha: ${{ github.event.pull_request.head.sha }}
          target_url: ${{ steps.get-url.outputs.url }}

      - name: Adding markdown
        run: |
          echo '[Allure report](${{ steps.get-url.outputs.url }})' >> $GITHUB_STEP_SUMMARY

  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
