name: All in one job

on:
  pull_request: ~
  push:
    branches:
      - master

jobs:
  everything:
    name: Do everything
    runs-on: ubuntu-latest
    steps:
      - name: Create
        run: |
          echo "Pretending to prepare files"
          touch file.txt
          echo "file content" >> file.txt

      - name: Check
        run: |
          echo "Pretending to run test"
          cat file.txt

      - name: Run semantic release
        if: github.event == 'push'
        steps:
          - name: Run semantic release
            run: echo "Pretending to run semantic release"
