name: All in one job

on:
  pull_request: ~
  push:
    branches:
      - master

jobs:
  log:
    name: Log data
    runs-on: ubuntu-latest
    steps:
      - name: GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"

      - name: Steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"

      - name: Runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"

      - name: Strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"

      - name: Matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

  build:
    name: 'Create build'
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: 'Install'
        run: echo 'Installing...'

      - name: '"Build package"'
        run: echo 'Building...'

      - name: Upload build
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: src/

  test:
    name: 'Run tests and update coverage'
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Get build
        uses: actions/upload-artifact@v1
        with:
          name: build

      - name: Run tests
        run: |
          cat dist/myparcel.js

  release:
    name: 'Create release and publish to npm'
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Get build
        uses: actions/upload-artifact@v1
        with:
          name: build

      - name: Run semantic release
        run: echo "Releasing..."

  deploy:
    name: Deploy sandbox
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Get build
        uses: actions/upload-artifact@v1
        with:
          name: build

      - name: '"Publish"'
        steps:
          - run: |
              echo 'Publishing...'
              cat src/CHANGELOG.md
              cat src/main.js
              cat src/lalala/myFile.js
