name: Run Cypress tests

on:
  workflow_dispatch:

jobs:
  e2e:
    name: 'Run e2e tests'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: cypress-io/github-action@v4
