name: 'Test composer cache speeds'

on:
  workflow_dispatch:

jobs:
  original-1:
    uses: edielemoine/npm-releaser-action/.github/workflows/--composer-install-original.yml@main
  original-2:
    needs: original-1
    uses: edielemoine/npm-releaser-action/.github/workflows/--composer-install-original.yml@main

  vendor-1:
    uses: edielemoine/npm-releaser-action/.github/workflows/--composer-install-vendor.yml@main
  vendor-2:
    needs: vendor-1
    uses: edielemoine/npm-releaser-action/.github/workflows/--composer-install-vendor.yml@main
