name: 'Test'

on:
  repository_dispatch:
    types: [ test ]

  workflow_dispatch:

jobs:
  test:
    uses: edielemoine/npm-releaser-action/.github/workflows/--run-tests-docker.yml@main
    with:
      image_name: myparcel/sdk-test
      image_key: php-sdk-test
      ref: ${{ github.event.inputs.ref || github.event.client_payload.pull_request.head.label || '' }}
      release: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      environment: |
        CI=${CI}
        API_KEY_NL=API_KEY_NL
        API_KEY_BE=API_KEY_BE
