name: 'Test yarn cache speeds'

on:
  workflow_dispatch:

concurrency:
  group: test-yarn-cache-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ###
  # current
  ###
  current-1:
    uses: ./.github/workflows/--yarn-install-current.yml
    with:
      cache-key: ${{ github.sha }}

  current-2:
    needs: current-1
    uses: ./.github/workflows/--yarn-install-current.yml
    with:
      cache-key: ${{ github.sha }}

  ###
  # setup-node
  ###
  setup-node-1:
    uses: ./.github/workflows/--yarn-install-setup-node.yml
    with:
      cache-key: ${{ github.sha }}

  setup-node-2:
    needs: setup-node-1
    uses: ./.github/workflows/--yarn-install-setup-node.yml
    with:
      cache-key: ${{ github.sha }}

  ###
  # cache-node-modules
  ###
  cache-node-modules-1:
    uses: ./.github/workflows/--yarn-install-cache-node-modules.yml
    with:
      cache-key: ${{ github.sha }}

  cache-node-modules-2:
    needs: cache-node-modules-1
    uses: ./.github/workflows/--yarn-install-cache-node-modules.yml
    with:
      cache-key: ${{ github.sha }}

  ###
  # cache-both
  ###
  cache-both-1:
    uses: ./.github/workflows/--yarn-install-cache-both.yml
    with:
      cache-key: ${{ github.sha }}

  cache-both-2:
    needs: cache-both-1
    uses: ./.github/workflows/--yarn-install-cache-both.yml
    with:
      cache-key: ${{ github.sha }}

  ###
  # cache-folder
  ###
  cache-folder-1:
    uses: ./.github/workflows/--yarn-install-cache-folder.yml
    with:
      cache-key: ${{ github.sha }}

  cache-folder-2:
    needs: cache-folder-1
    uses: ./.github/workflows/--yarn-install-cache-folder.yml
    with:
      cache-key: ${{ github.sha }}

  ###
  # gist
  ###
  gist-1:
    uses: ./.github/workflows/--yarn-install-gist.yml
    with:
      cache-key: ${{ github.sha }}

  gist-2:
    needs: gist-1
    uses: ./.github/workflows/--yarn-install-gist.yml
    with:
      cache-key: ${{ github.sha }}
