name: Test a workflow

on:
  pull_request: ~
  push:
    branches:
      - master
    paths:
      - src/*
      - package.json
      - package-lock.json

jobs:
  prepare:
    name: Prepare files
    runs-on: ubuntu-latest
    steps:
      - run: echo "Pretending to prepare files"

  test:
    name: Test and update coverage
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Run tests
        run: echo "Pretending to run test"

  publish:
    name: Run semantic release
    if: github.event == 'push'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Run semantic release
        run: echo "Pretending to run semantic release"
