name: All in one job

on:
  pull_request: ~
  push:
    branches:
      - master
      - protected/**/*

jobs:
  #  log:
  #    name: Log data
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: GitHub context
  #        env:
  #          GITHUB_CONTEXT: ${{ toJson(github) }}
  #        run: echo "$GITHUB_CONTEXT"
  #
  #      - name: Job context
  #        env:
  #          JOB_CONTEXT: ${{ toJson(job) }}
  #        run: echo "$JOB_CONTEXT"
  #
  #      - name: Steps context
  #        env:
  #          STEPS_CONTEXT: ${{ toJson(steps) }}
  #        run: echo "$STEPS_CONTEXT"
  #
  #      - name: Runner context
  #        env:
  #          RUNNER_CONTEXT: ${{ toJson(runner) }}
  #        run: echo "$RUNNER_CONTEXT"
  #
  #      - name: Strategy context
  #        env:
  #          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
  #        run: echo "$STRATEGY_CONTEXT"
  #
  #      - name: Matrix context
  #        env:
  #          MATRIX_CONTEXT: ${{ toJson(matrix) }}
  #        run: echo "$MATRIX_CONTEXT"

  test:
    name: 'Run tests'
    runs-on: ubuntu-latest
    steps:
      - name: SKIP CI
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        run: echo "I should be ignored if you used [skip ci] in your commit message"

      - name: Run tests
        run: |
          ls -la
          cat src/CHANGELOG.md
          cat src/main.js
          cat src/lalala/myFile.js

  push:
    name: Test pushing
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          branch: master

      - run: |
          echo "New content" >> src/CHANGELOG.md
          cat src/CHANGELOG.md
          git add .
          git commit -m "add new content"
          git push

      - name: Temporarily disable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@master
        if: always()
        with:
          access-token: ${{ secrets.GH_ADMIN_TOKEN }}

      - uses: actions/checkout@v2
        with:
          branch: protected/test-1

      - run: |
          echo "New content" >> src/CHANGELOG.md
          cat src/CHANGELOG.md
          git add .
          git commit -m "add new content"
          git push

      - name: Enable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@master
        if: always()  # Force to always run this step to ensure "include administrators" is always turned back on
        with:
          access-token: ${{ secrets.GH_ADMIN_TOKEN }}
