name: 'Release'

on:
  push:
    branches:
      - master
      - main

jobs:
  release:
    name: 'Release'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - uses: actions/checkout@v2
      - uses: myparcelnl/actions/yarn-install@v1
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - uses: actions/checkout@v2
        with:
          ref: develop

      - name: 'Rebase'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git rebase origin/main
          git push
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
