name: 'Run tests'
description: 'Run tests using a Dockerfile'

inputs:
  node_version:
    description: 'The Node.js version to use'
    default: '16'
    required: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
        persist-credentials: false

    - name: 'Create .env file'
      shell: bash
      run: |
        cat << EOF > .env
        ${{ inputs.environment }}
        EOF

    - uses: myparcelnl/actions/build-docker-image@v3
      id: docker
      with:
        image: ${{ inputs.image_name }}
        key: ${{ inputs.image_key || inputs.image_name }}
        docker_args: ${{ inputs.docker_args }}

    - name: 'Run Dockerfile'
      shell: bash
      run: docker run --env-file .env ${{ steps.docker.outputs.tagged_image }}

    - name: 'Get coverage file from container'
      shell: bash
      run: docker cp $(docker ps -alq):/app/clover.xml .

    - uses: actions/upload-artifact@v4
      if: hashFiles('clover.xml') != ''
      with:
        name: coverage
        path: clover.xml
        retention-days: 14
